version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './vol/elasticsearch/data:/usr/share/elasticsearch/data'
      - './vol/elasticsearch/logs:/usr/share/elasticsearch/logs'
  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    restart: unless-stopped
    command:
      --job-directory /opt/cortex/jobs
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/jobs'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './vol/cortex/application.conf:/etc/cortex/application.conf'
      - './vol/cortex/jobs:/opt/cortex/jobs'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'
  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: 'thehive4'
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - './vol/thehive/application.conf:/etc/thehive/application.conf'
      - './vol/thehive/data:/opt/thp/thehive/data'
      - './vol/thehive/index:/opt/thp/thehive/index'
    networks:
      - default
    command: '--no-config --no-config-secret'
  cassandra:
    image: 'cassandra:3.11'
    container_name: cassandra
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - './vol/cassandra/data:/var/lib/cassandra/data'
networks:
  default: null
